# Generated by Django 2.2 on 2021-06-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название продукта', max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание продукта', verbose_name='Описание')),
                ('price', models.FloatField(help_text='Цена за одну штуку', verbose_name='Цена')),
                ('quantity', models.IntegerField(help_text='Количество товара на складе', verbose_name='Количество')),
            ],
        ),
    ]
