# Generated by Django 2.2 on 2021-06-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_product_and_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock_quantity',
        ),
    ]
