# Generated by Django 2.2 on 2021-06-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
